### ISSUE TITLE
Tree brushes not working

### ISSUE THREAD

**Issue by TheLethalGoose** [ervinnnc/VoxelSniper#16]
Heyho :) 
From what i can see the tree brushes sadly don't work.
None of the different tree types are working.
I'm on paper 201 and java 8
Console gives me this error:

[00:17:47 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'b' in plugin VoxelSniper v6.1.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-201]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-201]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1034) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.thevoxelbox.voxelsniper.brush.TreeSnipeBrush.parseParameters(TreeSnipeBrush.java:94) ~[?:?]
        at com.thevoxelbox.voxelsniper.command.VoxelBrushCommand.doCommand(VoxelBrushCommand.java:104) ~[?:?]
        at com.thevoxelbox.voxelsniper.command.VoxelCommand.onCommand(VoxelCommand.java:40) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-201]
        ... 17 more

**Comment by StealWonders** [comment]
This has been fixed in eaabc63 I believe.

**Comment by Runningkls** [comment]
This hasn't been fixed
